window.AppDom = {
  addressInput: document.getElementById("address"),
  lookupBtn: document.getElementById("lookupBtn"),
  resultEl: document.getElementById("result"),
  txResultEl: document.getElementById("txResult"),
  txValueBtcEl: document.getElementById("txValueBtc"),
  txStatusSubEl: document.getElementById("txStatusSub"),
  txMetaIdEl: document.getElementById("txMetaId"),
  txMetaDateEl: document.getElementById("txMetaDate"),
  txMetaConfirmedAtEl: document.getElementById("txMetaConfirmedAt"),
  txMetaTimeToConfirmationEl: document.getElementById("txMetaTimeToConfirmation"),
  txMetaTimeSinceConfirmationEl: document.getElementById(
    "txMetaTimeSinceConfirmation",
  ),
  txMetaFeeEl: document.getElementById("txMetaFee"),
  txEmbeddedDataEl: document.getElementById("txEmbeddedData"),
  txMetaConfirmationsEl: document.getElementById("txMetaConfirmations"),
  errorEl: document.getElementById("error"),
  balanceBtcEl: document.getElementById("balanceBtc"),
  balanceUnconfirmedEl: document.getElementById("balanceUnconfirmed"),
  actionMenuBtn: document.getElementById("actionMenuBtn"),
  actionMenu: document.getElementById("actionMenu"),
  actionQrBtn: document.getElementById("actionQrBtn"),
  actionExportBtn: document.getElementById("actionExportBtn"),
  qrOverlay: document.getElementById("qrOverlay"),
  qrCanvas: document.getElementById("qrCanvas"),
  exportOverlay: document.getElementById("exportOverlay"),
  exportOverlayPhase: document.getElementById("exportOverlayPhase"),
  exportProgressDetail: document.getElementById("exportProgressDetail"),
  exportProgressBar: document.getElementById("exportProgressBar"),
  exportProgressPercent: document.getElementById("exportProgressPercent"),
  exportProgressTrack: document.querySelector(".export-overlay__progress"),
  cardEl: document.querySelector(".card"),
  metaAddressLabelEl: document.getElementById("metaAddressLabel"),
  metaAddressEl: document.getElementById("metaAddress"),
  metaAddressTypeEl: document.getElementById("metaAddressType"),
  metaExposedPubKeyEl: document.getElementById("metaExposedPubKey"),
  metaTransactionsEl: document.getElementById("metaTransactions"),
  metaLastTxDateEl: document.getElementById("metaLastTxDate"),
  timeSinceLastEl: document.getElementById("timeSinceLast"),
  blockHeightTooltipEl: document.getElementById("blockHeightTooltip"),
};